- name: 'Execute a script on all web server nodes'
  hosts: web_nodes
  tasks:
    -   name: 'Execute a script on all web server nodes'
        script: /tmp/install_script.sh
    
    # Update script to start httpd on all web servers
    -   name: 'Start httpd service'
        service: name=httpd state=started